Finish connect-database-phase with pymysql.
ntut-xuan/FastShop pull request #11
Opened 2022-09-23 08:12 UTC by ntut-xuan

- 將後端連接至 `MariaDB`。
- 建立了 `database/database_util.py`，用於連接資料庫。
- 經過 `app.py` 上連接測試，確定無虞，若連接失敗時，網頁應用程式將會停止運作。

2022-09-23 09:59 UTC, Lai-YT commented
我稍後會實際運行，不過目前有一點需要調整

1. 我們遵守 [PEP 8 – Style Guide for Python Code](https://peps.python.org/pep-0008/) 的風格規範，在 `import` 的地方應該先匯入標準函式庫，再來第三方函式庫，最後才是本地／自撰的函式庫，[而這三個部分間應該「空一行」](https://peps.python.org/pep-0008/#imports)。總歸來說 [Black](https://black.readthedocs.io/en/stable/) 就是 PEP 8 的實踐，可以用以下指令來自動排版。

```bash
$ black .
```

如果使用 Visual Studio Code，快捷鍵 *shift + alt + f* 也可以自動排版（我用這個）。

之後我會發一個 `pre-commit` 的 PR，每次 commit 的時候都會自動檢查 code style 並且強制套用規範。

以及一點需要討論

1. 我看到 *backend/database/database_util.py*，*database_util* 的前綴 *database_* 拿掉的話你覺得會不會比較簡潔呢？還是說 *database/* 下會有其他種類的 *util*，那就必須要保留。

2022-09-23 11:39 UTC, Lai-YT commented
不過我在思考，資料庫測試是不是在整合測試的領域了，如果是 `connect_database` 函式的單元測試，我會用 mock 的。以及如果要測試和實際資料庫的互動，可能會需要一個測試用的資料庫，並且每次測試都能還原到一樣的狀態。
會不會我們需要一個 dev-docker-compose.yml，其中有測試用的資料庫，然後每次測試時都運行腳本，來設定 data 以及清除還原（設定不寫在 yaml 中）。

2022-09-23 12:30 UTC, ntut-xuan commented
我覺得理論上應該可以，在我的舊專案上是使用單元測試，每次會造假資料（setup）跟刪除假資料（teardown）。
如果可以開一個 docker 來當作 dev 測試的話應該會很棒，可以考慮加到新的 issues 上。

2022-09-23 12:55 UTC, Lai-YT requested changes
會是這個樣子的

2022-09-23 12:55 UTC, Lai-YT commented on backend/app.py
> +from database.util import connect_database
```python
from pathlib import Path
from secrets import token_hex
from typing import Any, Mapping

from flask import Flask

from database.util import connect_database
```

2022-09-23 15:14 UTC, ntut-xuan commented on backend/app.py
> +from database.util import connect_database
已在 b3ac30d218bda275ed430bcbf5ef502426031013 修正

2022-09-24 03:12 UTC, Lai-YT commented
目前的資料庫連接測試依賴實際運行的 MariaDB，這導致我們不能自動化測試。
我會在 unit test 的時候把這個部分 mock 掉；實際連接的測試預計之後再 issue 一個 integration test 去處理。

2022-09-24 04:39 UTC, ntut-xuan reviewed
LGTM

2022-09-24 05:40 UTC, Lai-YT approved these changes
Done. Let's merge this *PR*.

2022-09-24 05:41 UTC, merged