Create models of shopping_cart, order and item_of_order
ntut-xuan/FastShop pull request #159
Opened 2023-01-04 01:07 UTC by Lai-YT

## What's new?

新增了 3 個 table，分別是 `shopping_cart`, `order` 和 `item_of_order`。

### SQL statements

這些 table 是用 SQLAlchemy 的 interface 建立的，實際執行轉換成 MariaDB 的 SQL 後有以下敘述：

```sql
CREATE TABLE shopping_cart (
    user_id INTEGER NOT NULL, 
    item_id INTEGER NOT NULL, 
    count INTEGER NOT NULL, 
    PRIMARY KEY (user_id, item_id), 
    CHECK (count > 0), 
    FOREIGN KEY(user_id) REFERENCES user (uid) ON DELETE CASCADE ON UPDATE CASCADE, 
    FOREIGN KEY(item_id) REFERENCES item (id) ON DELETE CASCADE ON UPDATE CASCADE
)

CREATE TABLE `order` (
    order_id INTEGER NOT NULL AUTO_INCREMENT, 
    user_id INTEGER, 
    date INTEGER NOT NULL, 
    order_status ENUM('CANCEL','CHECKING','OK') NOT NULL, 
    delivery_status ENUM('DELIVERED','DELIVERING','PENDING','SKIP') NOT NULL, 
    delivery_address TEXT NOT NULL, 
    note TEXT, 
    phone VARCHAR(10) NOT NULL, 
    PRIMARY KEY (order_id), 
    FOREIGN KEY(user_id) REFERENCES user (uid) ON DELETE CASCADE ON UPDATE CASCADE
)

CREATE TABLE item_of_order (
    order_id INTEGER NOT NULL, 
    item_id INTEGER NOT NULL, 
    count INTEGER NOT NULL, 
    PRIMARY KEY (order_id, item_id), 
    CHECK (count > 0), 
    FOREIGN KEY(order_id) REFERENCES `order` (order_id) ON DELETE CASCADE ON UPDATE CASCADE, 
    FOREIGN KEY(item_id) REFERENCES item (id) ON DELETE CASCADE ON UPDATE CASCADE
)
```
`order_status` 和 `delivery_status` 兩個欄位背後有 Python 的 `Enum`, SQLALchemy 會自動進行轉換。

### Tables

table 建立後於 MariaDB 中 `DESCRIBE` 的樣子如下：

```
shopping_cart
+---------+---------+------+-----+---------+-------+
| Field   | Type    | Null | Key | Default | Extra |
+---------+---------+------+-----+---------+-------+
| user_id | int(11) | NO   | PRI | NULL    |       |
| item_id | int(11) | NO   | PRI | NULL    |       |
| count   | int(11) | NO   |     | NULL    |       |
+---------+---------+------+-----+---------+-------+

`order`
+------------------+-------------------------------------------------+------+-----+---------+----------------+
| Field            | Type                                            | Null | Key | Default | Extra          |
+------------------+-------------------------------------------------+------+-----+---------+----------------+
| order_id         | int(11)                                         | NO   | PRI | NULL    | auto_increment |
| user_id          | int(11)                                         | YES  | MUL | NULL    |                |
| date             | int(11)                                         | NO   |     | NULL    |                |
| order_status     | enum('CANCEL','CHECKING','OK')                  | NO   |     | NULL    |                |
| delivery_status  | enum('DELIVERED','DELIVERING','PENDING','SKIP') | NO   |     | NULL    |                |
| delivery_address | text                                            | NO   |     | NULL    |                |
| note             | text                                            | YES  |     | NULL    |                |
| phone            | varchar(10)                                     | NO   |     | NULL    |                |
+------------------+-------------------------------------------------+------+-----+---------+----------------+

item_of_order
+----------+---------+------+-----+---------+-------+
| Field    | Type    | Null | Key | Default | Extra |
+----------+---------+------+-----+---------+-------+
| order_id | int(11) | NO   | PRI | NULL    |       |
| item_id  | int(11) | NO   | PRI | NULL    |       |
| count    | int(11) | NO   |     | NULL    |       |
+----------+---------+------+-----+---------+-------+
```

## How has This been tested?

3 組測資針對 `count > 0` 的 check constraint 以及 enum 的轉換去確認，在 SQLite 與 MariaDB 環境下皆通過測試。

- [x] `shopping_cart` 中的 `count` 不為正時會拋例外
- [x] `item_of_order` 中的 `count` 不為正時會拋例外
- [x] `order` 中的 `order_status` 和 `delivery_status` 可使用 `Enum` 新增，查詢出來時也是 `Enum`

**NOTE**: 不同的資料庫遇到 check constriant 不符合時所拋出的例外型別可能不同（SQLIte 是 IntegrityError 而 MariaDB 是 OperationalError），因此接例外時接他們的 Base type 來確保能相容。

2023-01-04 01:45 UTC, ntut-xuan commented
``
| user_id          | int(11)                                         | YES  | MUL | NULL    |                |
```

我想訂單一定要有擁有者，所以我認為 nullable 應該要是 NO。

2023-01-04 01:51 UTC, ntut-xuan requested changes

2023-01-04 01:51 UTC, ntut-xuan commented on backend/models/__init__.py
> +    user_id = db.Column(db.ForeignKey(User.uid, ondelete="CASCADE", onupdate="CASCADE"))
基於訂單一定是由使用者所創立，故每筆訂單必定會有使用者，`user_id` 的 nullable 應為 NO。
```suggestion
    user_id = db.Column(db.ForeignKey(User.uid, ondelete="CASCADE", onupdate="CASCADE", nullable=False))
```

2023-01-04 06:14 UTC, Lai-YT commented on backend/models/__init__.py
> +    user_id = db.Column(db.ForeignKey(User.uid, ondelete="CASCADE", onupdate="CASCADE"))
已於 f26cbf814b2d648854095d8ec6240277709f242f 修正。
其中 nullable 是 `db.Column` 的參數而非 `db.ForeignKey` 的參數，因此進行了小調整。

2023-01-05 01:38 UTC, ntut-xuan commented on backend/models/__init__.py
> +    count = db.Column(db.Integer, nullable=False)
若 count 不存在，設定 default 為 0。
```suggestion
    count = db.Column(db.Integer, nullable=False, default=0)
```

2023-01-05 01:46 UTC, Lai-YT commented on backend/models/__init__.py
> +    count = db.Column(db.Integer, nullable=False)
我覺得 order 中的 item 數量不應該為 0，下一個商品數量為 0 的訂單不合理，所以也有一個 check constraint 在檢查 count  > 0

2023-01-05 01:50 UTC, ntut-xuan approved these changes

2023-01-05 01:54 UTC, merged