JWT cookie 實作
ntut-xuan/FastShop pull request #44
Opened 2022-10-28 17:02 UTC by ntut-xuan

- 當使用者登入成功時，會得到一 JWT cookie，得到一個由 email、產生時間與有效期限組成的 payload，格式如下：

```
{
  "data": {
    "birthday": 1666604387,
    "e-mail": "test@email.com",
    "firstname": "Han-Xuan",
    "gender": 0,
    "lastname": "Huang"
  },
  "iat": 1666976488,
  "exp": 1667062888
}
```

2022-10-29 05:32 UTC, Lai-YT commented on backend/auth/route.py
> +    fetch_specific_account_profile,
請以字典順序排列模組

```diff
from auth.util import (
    BIRTHDAY_FORMAT,
    UserProfile,
+   fetch_specific_account_profile,
+   generate_payload,
    is_valid_birthday_format,
    is_valid_email,
    login,
    register,
)

2022-10-29 05:37 UTC, Lai-YT commented on backend/auth/route.py
> +def _make_response_with_jwt_cookie(data: dict, response: Response):
做的事情其實是設定 cookie 而不是產生新的 `Response`，因此建議命名為 `_set_jwt_cookie_to_response()` ，然後不回傳，因為 `set` 表示了這個函式將直接更動 argument。

2022-10-29 05:38 UTC, Lai-YT commented on backend/auth/route.py
> +    response.set_cookie("cd_wy_sbl", value=jwt_data, expires=expire_time)
`"cd_wy_sbl"` 有什麼特別的涵義嗎？

2022-10-29 05:40 UTC, Lai-YT commented on backend/auth/route.py
> +    jwt_data = generate_payload(data)
標示一下 `jwt_data` 的型別，因為 `generate_payload` 這個名字並沒有顯示（explicitly）透露回傳型別。

2022-10-29 05:42 UTC, Lai-YT commented on backend/auth/route.py
> +    expire_time: datetime = current_time + timedelta(days=1)
變數命名不使用動詞，建議改為 `expiration_time`

2022-10-29 05:45 UTC, Lai-YT commented on backend/auth/util.py
> +import jwt
第三方模組放在標準模組與自己的模組之間

```python
import hashlib
import re
# blank line
import jwt
#blank line
from auth.exception import ...
```

2022-10-29 05:51 UTC, Lai-YT commented on backend/auth/util.py
> +    """Return the jwt data is valid or not."""
Docsting 的 summary 以動詞開頭，且以「(this function) does something」的方式撰寫，因此使用 `Returns` 取代 `Return`。
可參考 [Google Python Style Guide - functions-and-methods](https://google.github.io/styleguide/pyguide.html#383-functions-and-methods)

2022-10-29 05:55 UTC, Lai-YT commented on backend/auth/util.py
> +    except jwt.exceptions.ExpiredSignatureError:
因為都是回傳 `False`，可用以下方式簡化

```python
try:
    # something
except (jwt.DecodeError, jwt.exceptions.ExpiredSignatureError):
    return False
```

2022-10-29 05:59 UTC, Lai-YT commented on backend/auth/util.py
> +    data: dict, expire_time_delta: timedelta = timedelta(days=1)
`expire_time_delta` 可改為 `expiration_time_delta`

2022-10-29 06:00 UTC, Lai-YT commented on backend/auth/util.py
> +    """Return the payload with generate time attribute (iat) and 1 day expired strict attribute (exp)."""
`exp` 是參數之一，不一定是 1 天，所以不在 docstring 中寫死。

2022-10-29 06:37 UTC, Lai-YT commented on backend/auth/util.py
> +    return jwt.decode(data, "secret", algorithms=["HS256"])
`decode` 和 `encode` 時都使用 `"secret"` 和 `"HS256"`，考慮包裝成類別，將他們升級成 attribute 或 class variable 來確保一致性。

2022-10-29 06:42 UTC, Lai-YT commented on backend/auth/util.py
> +        UserNotFoundError: The `email` in parameter isn't register yet.
用 backticks（‵‵）標記的字本身就有 parameter 的意思了，可以考慮改成

```
No registered user with email `email`.
```

或

```
The `email` doesn't belong to any registered user.
```

2022-10-29 06:46 UTC, Lai-YT commented on backend/auth/util.py
> +def fetch_specific_account_profile(email: str) -> dict:
return type 可以更精確地使用 `dict[str, Any]` ，因為 `execute_command` 取得的 key 一定是字串。

2022-10-29 06:49 UTC, Lai-YT commented on backend/tests/test_auth.py
> +    fetch_specific_account_profile,
請用以下方式 import 模組，分成三個區段

```python
import standard_library
# blank line
import third_party_library
# blank line
import self_defined_library
```

區段間以字典順序排列

2022-10-29 06:51 UTC, Lai-YT commented on backend/tests/test_auth.py
> +        new_data: dict[str, str],
字典的 value 有可能是 `int`

```python
new_data: dict[str, str | int]
```

2022-10-29 06:53 UTC, Lai-YT commented on requirements.txt
> +distro==1.7.0
`distro` 不是 `PyJWT` 的相依套件，請移除

2022-10-29 07:01 UTC, Lai-YT commented on backend/tests/test_auth.py
> +    def test_using_profile_fetch_function_with_unregister_email(
可以將 class name 改成 `TestFetchSpecificAccountProfile`，而後測試函式叫做 `test_with_unregistered_email_should_raise_exception` 即可。在先前的設計中，我將目標函式的名稱直接編入 class name 中，不再重複編入測試函式的名字中。

2022-10-29 07:08 UTC, Lai-YT commented on backend/tests/test_auth.py
> +                fetch_specific_account_profile("c8763@ccc.nnn")
建議使用 explaining variable，即以下形式

```python
# Arrange
unregistered_email: str = "c8763@ccc.nnn"
with app.app_context():
    # Act
    with pytest.raises(UserNotFoundError):
        # Assert
        fetch_specific_account_profile(unregistered_email)
```
並利用空行（將註解移除，空行即可）來將 [AAA](https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-best-practices#arranging-your-tests) 的三個區塊給分開，

2022-10-29 07:09 UTC, Lai-YT commented on backend/tests/test_auth.py
> +class TestJWTFunction:
改成 `TestIsValidJwtData`

2022-10-29 07:10 UTC, Lai-YT commented on backend/tests/test_auth.py
> +    def test_if_data_invalid_validation_should_return_false(self) -> None:
改成 `test_on_invalid_data_should_return_false`

2022-10-29 07:11 UTC, Lai-YT commented on backend/tests/test_auth.py
> +        assert is_valid_jwt_data(some_jwt_key) == False
以 `assert not ...` 取代 `assert ... == False`

2022-10-29 07:12 UTC, Lai-YT commented on backend/tests/test_auth.py
> +    def test_if_data_not_have_enought_segment_validation_should_return_false(
文法不太對，改成 `test_on_data_with_not_enough_segment_should_return_false`，其中 `data_with_not_enough_segment` 描述測資

2022-10-29 07:15 UTC, Lai-YT commented on backend/tests/test_auth.py
> +    def test_if_data_expired_validation_should_return_false(self) -> None:
這個測試的重點是 negative expiration time 嗎？是的話建議重新命名，然後用 explaining variable 強調 negative expiration time。

2022-10-29 07:16 UTC, Lai-YT requested changes
請根據 commet 中的內容進行修改，或進行討論。

2022-10-29 07:29 UTC, ntut-xuan commented on backend/auth/route.py
> +    fetch_specific_account_profile,
已在 571720c 修復。

2022-10-29 07:31 UTC, ntut-xuan commented on backend/auth/route.py
> +def _make_response_with_jwt_cookie(data: dict, response: Response):
已在 fc474a5 修復

2022-10-29 07:32 UTC, ntut-xuan commented on backend/auth/route.py
> +    response.set_cookie("cd_wy_sbl", value=jwt_data, expires=expire_time)
ci_di_wu_yin_san_bai_liang (此地無銀三百兩) 的簡寫，

2022-10-29 07:36 UTC, ntut-xuan commented on backend/auth/route.py
> +    expire_time: datetime = current_time + timedelta(days=1)
已在 de0e249 修復。

2022-10-29 07:36 UTC, ntut-xuan commented on backend/auth/util.py
> +    data: dict, expire_time_delta: timedelta = timedelta(days=1)
已在 de0e249 修復。

2022-10-29 07:39 UTC, ntut-xuan commented on backend/auth/util.py
> +import jwt
已在 eecc1f04222c42d683d2251dfdd74bfab9354800 修復

2022-10-29 07:41 UTC, ntut-xuan commented on backend/auth/util.py
> +    except jwt.exceptions.ExpiredSignatureError:
已在 82e1fac77f0fcc8620a89418557fc29436d88af7 修復

2022-10-29 07:45 UTC, ntut-xuan commented on backend/auth/util.py
> +        UserNotFoundError: The `email` in parameter isn't register yet.
已在 fca5167 修復。

2022-10-29 07:45 UTC, ntut-xuan commented on backend/auth/util.py
> +    """Return the payload with generate time attribute (iat) and 1 day expired strict attribute (exp)."""
已在 https://github.com/ntut-xuan/FastShop/commit/fca5167057743bb137928a199f4a7c7d2a90e0e8 修復。

2022-10-29 07:46 UTC, ntut-xuan commented on backend/auth/util.py
> +    """Return the jwt data is valid or not."""
已在 https://github.com/ntut-xuan/FastShop/commit/fca5167057743bb137928a199f4a7c7d2a90e0e8 修復。

2022-10-29 07:48 UTC, Lai-YT commented on backend/auth/route.py
> +def _make_response_with_jwt_cookie(data: dict, response: Response):
然後回傳 None 的部分你覺得如何呢？

2022-10-29 07:59 UTC, ntut-xuan commented on backend/auth/route.py
> +    jwt_data = generate_payload(data)
已在 b7574d0 復

2022-10-29 08:10 UTC, Lai-YT commented on backend/auth/route.py
> +    response.set_cookie("cd_wy_sbl", value=jwt_data, expires=expire_time)
用 `"jwt"` 取代吧～不需要特別藏

2022-10-29 08:11 UTC, ntut-xuan commented on backend/auth/route.py
> +def _make_response_with_jwt_cookie(data: dict, response: Response):
ok！我這邊做修改。

2022-10-29 08:12 UTC, ntut-xuan commented on backend/auth/route.py
> +    response.set_cookie("cd_wy_sbl", value=jwt_data, expires=expire_time)
已在 6f669df 修復

2022-10-29 08:21 UTC, ntut-xuan commented on backend/auth/route.py
> +def _make_response_with_jwt_cookie(data: dict, response: Response):
已在 a2242dc 做修復。

2022-10-29 10:53 UTC, ntut-xuan commented on backend/auth/util.py
> +    return jwt.decode(data, "secret", algorithms=["HS256"])
已於 f68fbc7 、 cf5dac0 、 89f245f 修正。

2022-10-29 10:58 UTC, ntut-xuan commented on backend/auth/util.py
> +def fetch_specific_account_profile(email: str) -> dict:
已於 f22b68f 修復。

2022-11-01 07:18 UTC, ntut-xuan commented on backend/tests/test_auth.py
> +    fetch_specific_account_profile,
已在 250ce6d ， 1216a50 修復

2022-11-01 07:21 UTC, ntut-xuan commented on backend/tests/test_auth.py
> +        new_data: dict[str, str],
已在 ecf21ec 修復。

2022-11-01 07:23 UTC, ntut-xuan commented on requirements.txt
> +distro==1.7.0
已在 468289c 修復

2022-11-01 07:25 UTC, ntut-xuan commented on backend/tests/test_auth.py
> +    def test_using_profile_fetch_function_with_unregister_email(
已於 e0ad608 修復

2022-11-01 07:28 UTC, ntut-xuan commented on backend/tests/test_auth.py
> +                fetch_specific_account_profile("c8763@ccc.nnn")
已於 902669d 修復

2022-11-01 07:30 UTC, ntut-xuan commented on backend/tests/test_auth.py
> +class TestJWTFunction:
JWT 是 JSON Web Token 的縮寫，用全大寫似乎比較合乎大寫駝峰的概念。

2022-11-01 07:32 UTC, ntut-xuan commented on backend/tests/test_auth.py
> +    def test_if_data_invalid_validation_should_return_false(self) -> None:
已於 22f7687 修復。

2022-11-01 07:33 UTC, ntut-xuan commented on backend/tests/test_auth.py
> +        assert is_valid_jwt_data(some_jwt_key) == False
已於 7907d7f 修復

2022-11-01 07:35 UTC, ntut-xuan commented on backend/tests/test_auth.py
> +    def test_if_data_not_have_enought_segment_validation_should_return_false(
已於 0b68096 修復。

2022-11-01 07:37 UTC, ntut-xuan commented on backend/tests/test_auth.py
> +    def test_if_data_expired_validation_should_return_false(self) -> None:
於 fe1f811 修復

2022-11-01 07:55 UTC, ntut-xuan commented on backend/tests/test_auth.py
> +class TestJWTFunction:
經討論後採用 `TestIsValidJWTData`，已於 3275a4e 修復。

2022-11-01 09:14 UTC, Lai-YT commented on backend/auth/util.py
> +def generate_payload(
回傳的東西其實是 JWT，可以將名字改為 `generate_jwt_from_data`

2022-11-01 09:15 UTC, Lai-YT commented on backend/auth/util.py
> +    jwt_payload: str = jwt.encode(payload, JWTCodec.key, algorithm=JWTCodec.algorithm)
encode 之後就是個 token 了，建議變數名稱改為
```python
token: str = jwt.encode(...)
return token
```

2022-11-01 09:21 UTC, Lai-YT commented on backend/auth/util.py
> +    """Returns the payload with generate time attribute (iat) and specific-date expiration strict attribute (exp)."""
不太清楚 iat 和 exp 的描述（文法可能也不太對），同時因為回傳的是 JWT 不是 payload，可以參考以下 docstring：

```python
"""Returns the JWT with `data`, Issue At (iat) and Expiration Time (exp) as payload."""
```

2022-11-01 09:26 UTC, Lai-YT commented on backend/auth/util.py
> +def decode_jwt(data: str) -> dict:
`decode_jwt` 和上面 `generate_payload` 的作用是相對的嗎？如果是的話，能否在命名上表現出這一點

2022-11-01 09:28 UTC, Lai-YT commented on backend/auth/util.py
> +class JWTCodec:
`Codec` 這個名字不適合 dataclass，同時他的 data 的預設值被當成了 global 變數使用。建議將會使用這些變數的 function 升級為 `JWTCodec` 的 method，提供良好的封裝及一致性。

2022-11-01 13:46 UTC, Lai-YT commented on backend/auth/util.py
> +class JWTCodec:
於 ad364f21b1ffac27f5f4b5a018b57efead010282 中完成封裝

2022-11-01 13:49 UTC, Lai-YT commented on backend/auth/util.py
> +def fetch_specific_account_profile(email: str) -> dict[str, Any]:
目前回傳 `dict` 比較方便所以不修改，get/fetch 的部分暫不調整，在 d07ef3b786144fd0f9d577d83fdd61c7aa5e385c 調整了命名。

2022-11-01 13:49 UTC, Lai-YT commented on backend/auth/util.py
> +    """Returns the payload with generate time attribute (iat) and specific-date expiration strict attribute (exp)."""
於 ad364f21b1ffac27f5f4b5a018b57efead010282 中修改

2022-11-01 13:50 UTC, Lai-YT commented on backend/auth/util.py
> +def generate_payload(
於 ad364f21b1ffac27f5f4b5a018b57efead010282 中封裝後改名成 `encode`

2022-11-01 15:22 UTC, Lai-YT commented on backend/auth/util.py
> +    jwt_payload: str = jwt.encode(payload, JWTCodec.key, algorithm=JWTCodec.algorithm)
在 ad364f21b1ffac27f5f4b5a018b57efead010282 修改了名稱

2022-11-01 16:39 UTC, Lai-YT commented
和 JWT 的 encode / decode 相關的測試會依賴於實際的時間，因為不同的時間的 expiration time 是不一樣的，編碼後也會不一樣。目前 skip 掉了，需要使用 [FreezeGun](https://github.com/spulec/freezegun) 凍結時間。

2022-11-02 07:06 UTC, Lai-YT approved these changes

2022-11-02 07:19 UTC, merged