新增 apidocs 頁面，完成 API 整理文件
ntut-xuan/FastShop pull request #73
Opened 2022-11-29 15:06 UTC by ntut-xuan

### Brief Description

我們在這個 PR 中，引入了 Swagger API documentation 來幫助設計 API 的說明文件。

### The one thing you should do before you review the PR

使用 `pip` 安裝 `flasgger`，使用指令 `pip install flasgger` 來安裝。

### The things we finish in this PR

 - 完成目前的 6 個 `route` 文件建置。
 - 使目前的 `apidocs` 頁面可以正常運作。

也許未來可以引入 Restful API 的機制？

Resolved: #72

2022-11-30 09:14 UTC, Lai-YT requested changes
另外我希望可以在 api 的 folder 中放個說明的 markdown，至少要說明去哪個 route 看 apidocs XD

2022-11-30 09:14 UTC, Lai-YT commented on backend/api/verify_jwt_post.yml
> +      description: The response message from server.
from **the** server

2022-11-30 09:14 UTC, Lai-YT commented on backend/app.py
> +from flasgger import Swagger
g 的字典順序在 k 之前，需要換一下

2022-11-30 09:14 UTC, Lai-YT commented on backend/app.py
> +    Swagger(app)
考慮用一個 `init_swagger(app: Flask)` 的函式把上面這些改動搬移進去嗎？
我認為 `Swagger` 作為一個 documentation 的工具，不應該在 `create_app` 占用這麼大的空間，且 swagger_config 是很細節的東西了。

2022-12-01 00:36 UTC, ntut-xuan commented on backend/app.py
> +    Swagger(app)
Solved on 3697008.

2022-12-01 00:36 UTC, ntut-xuan commented on backend/app.py
> +from flasgger import Swagger
Solved on 15b1af3.

2022-12-01 00:54 UTC, ntut-xuan commented on backend/api/verify_jwt_post.yml
> +      description: The response message from server.
Solved on 89cf1cc.

2022-12-01 00:55 UTC, ntut-xuan commented on backend/api/verify_jwt_post.yml
> +description: Verify the jwt cookie in the header, if it is absent or invalid should return an error.
Solved on 89cf1cc.

2022-12-01 00:55 UTC, ntut-xuan commented on backend/api/register_post.yml
> +      lastname:
Solved on 89cf1cc.

2022-12-01 00:55 UTC, ntut-xuan commented on backend/api/register_post.yml
> +        exmaple: "2002-06-25"
Solved on 89cf1cc.

2022-12-01 00:55 UTC, ntut-xuan commented on backend/api/register_post.yml
> +        description: The response message from server.
Solved on 89cf1cc.

2022-12-01 00:55 UTC, ntut-xuan commented on backend/api/register_post.yml
> +description: Post the register payload to backend server.
Solved on 89cf1cc.

2022-12-01 00:55 UTC, ntut-xuan commented on backend/api/register_get.yml
> +description: Get the register page from backend server.
Solved on 89cf1cc.

2022-12-01 00:55 UTC, ntut-xuan commented on backend/api/logout_post.yml
> +      description: The response message from server.
Solved on 89cf1cc.

2022-12-01 00:57 UTC, ntut-xuan commented
在 `backend/api` 新增了 `README.md`，用於說明怎麼找到 `apidocs` 的連結以及一些編寫的相關規定。

2022-12-01 01:28 UTC, Lai-YT approved these changes
LGTM :smiley:

2022-12-01 01:54 UTC, Lai-YT approved these changes
Love the extraction :heart:

2022-12-01 04:05 UTC, merged