完成 tags 的 API 描述
ntut-xuan/FastShop pull request #90
Opened 2022-12-03 13:02 UTC by ntut-xuan

## Brief Description

在這份 PR 中，我們帶來了有關 `tags` 的初步描述以及 function signature。

## Preview

Checkout 到這個 branch，接著使用瀏覽器打開 `http://localhost:8080/apidocs`。

## What's new?

新增了六個 `tags` 的介面。

 - `GET /tags/`：取得所有 tag。
 - `POST /tags/`：新增一個 tag。
 - `GET /tags/{ID}/` 根據 tag ID 取得一個 tag。
 - `PUT /tags/{ID}/` 根據 tag ID 更新一個 tag。
 - `DELETE /tags/{ID}/` 根據 tag ID 刪除一個 tag。
 - `GET /tags/{ID}/items/` 根據 tag ID 取得所有具有該 tag 的物品。

## Postscript

由於我英文頗爛，請幫我注意一下文法問題，感恩 orz

2022-12-03 13:46 UTC, Lai-YT requested changes

2022-12-03 13:46 UTC, Lai-YT commented on backend/app.py
> +from tag.route import tag_bp
需要按照字典排序調換一下

2022-12-04 01:42 UTC, Lai-YT requested changes

2022-12-04 01:42 UTC, Lai-YT commented on backend/api/tags_get.yml
> +        items:
這邊用 `items` 可能有點混淆，要用 `tags` 嗎？

2022-12-04 01:42 UTC, Lai-YT commented on backend/api/tags_id_items_get.yml
> +          $ref: '#/definitions/tag_response'
是不是應該回傳 items 而非 tags 呢？

2022-12-04 01:44 UTC, ntut-xuan commented on backend/api/tags_get.yml
> +        items:
描述 array 內部的東西應該要用 items
只有最上層的 attribute 才是 schemaID

2022-12-04 11:32 UTC, Lai-YT commented on backend/api/tags_get.yml
> +        items:
嗯… 所以 return 的 payload 這樣是正確的嗎？
![image](https://user-images.githubusercontent.com/52515370/205487981-c2c0045e-1f03-4f4e-8467-12a98c783ecc.png)

2022-12-04 11:44 UTC, ntut-xuan commented on backend/api/tags_get.yml
> +        items:
Got it, 應該要叫做 `tags` 比較好，我做點小修改

2022-12-04 11:50 UTC, Lai-YT commented on backend/api/tags_get.yml
> +        items:
噢噢我應該標上面那個 items，下面那個是 swagger 的識別字 😭

2022-12-04 11:54 UTC, Lai-YT approved these changes
LGTM

2022-12-04 11:57 UTC, merged